### PR TITLE
Implemented bar-chart + 2 widgets

### PR DESCRIPTION
**Pull request by ImLuisAyala**
- Created new page for data visualization (bar-chart & line-chart)
- Implemented bar-chart class
- Created warning message, as requested by professor, to notify of static data
- Created two widgets for bar-chart customization (slider)

### CODE REVIEW

**Review by houyhourung — APPROVED** [review]
looks good but the widgets is not really working

**Comment by CarolinaMartine5** [comment]
Looks good to me.

**Review by CarolinaMartine5 — CHANGES_REQUESTED** [review]
The widgets do not work nor add anything. Fix.

**Review by houyhourung — CHANGES_REQUESTED** [review]
the slider widget is not working

**Pull request closed without merging**
